spring:
  application:
    name: joblens-email-filter
  mail:
    host: smtp.gmail.com
    port: 587
    username: perumalraj024@gmail.com
    password: obsd ocys xbjd vtpt

    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 30000
          timeout: 30000
          writetimeout: 30000

gmail:
  oauth:
    client-id: 956600029837-4ds3lc3vibf1iplg1i0mir7qpoq8ia4d.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:8888/callback
    token-file-path: tokens/
    scopes: https://www.googleapis.com/auth/gmail.readonly
  lookback-hours: 24
  max-emails-per-run: 20
  query:
    subject-terms:
      - jobs
      - recommended
      - opportunities

job:
  keywords: java,spring,spring boot,backend,rest,oracle,microservices,api
  
  experience:
    min: 0
    max: 10
  
  max-results: 10
  
  filter:
    min-experience: 0
    max-experience: 10
  
  email:
    send-to: perumalraj024@gmail.com
    subject: "JobLens - Top 10 Opportunities (Last 24h)"
    from: perumalraj024@gmail.com
    subject-prefix: "JobLens -"

openai:
  api-key: ${OPENAI_API_KEY:}
  model: gpt-4o-mini
  temperature: 0.0
  max-tokens: 700

resume:
  file-path: resume.pdf

scheduling:
  email-fetcher:
    cron: "*/10 * * * * *"

logging:
  level:
    root: INFO
    com.joblens: DEBUG
    com.google.api: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
